-- Stores generated Home Assistant YAML configurations per user
CREATE TABLE IF NOT EXISTS yaml_configs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  prompt TEXT NOT NULL DEFAULT '',
  yaml TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fast lookup by user, newest first
CREATE INDEX IF NOT EXISTS yaml_configs_user_id_created_idx
  ON yaml_configs (user_id, created_at DESC);

-- RLS: each user can only see and manage their own configs
ALTER TABLE yaml_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own yaml configs"
  ON yaml_configs FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own yaml configs"
  ON yaml_configs FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own yaml configs"
  ON yaml_configs FOR DELETE
  USING (auth.uid() = user_id);

COMMENT ON TABLE yaml_configs IS 'User-saved Home Assistant YAML automations generated by the AI tool';
